-- ========================================
-- 1.環境構築
-- ========================================
create or replace database application_db;
create or replace schema application_db.application_schema;
use schema application_db.application_schema;

-- ========================================
-- 2.バックエンドテーブル作成
-- ========================================
-- 定型検索のバックエンドテーブル
create or replace TABLE STANDARD_SEARCH_OBJECTS (
	OBJECT_ID VARCHAR(16777216),
	OBJECT_NAME VARCHAR(16777216),
	DESCRIPTION VARCHAR(16777216),
	SEARCH_QUERY VARCHAR(16777216),
	CREATED_BY VARCHAR(16777216)DEFAULT CURRENT_USER(),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	IS_FAVORITE BOOLEAN DEFAULT FALSE,
	EXECUTION_COUNT NUMBER(38,0) DEFAULT 0,
	LAST_EXECUTED TIMESTAMP_NTZ(9)
);

-- 非定型検索のバックエンドテーブル
CREATE OR REPLACE TABLE ADHOC_SEARCH_OBJECTS (
	OBJECT_ID VARCHAR(16777216),
	OBJECT_NAME VARCHAR(16777216),
	DESCRIPTION VARCHAR(16777216),
	TABLE1_NAME VARCHAR(16777216),
	TABLE2_NAME VARCHAR(16777216),
	JOIN_TYPE VARCHAR(100),
	JOIN_KEY1 VARCHAR(16777216),
	JOIN_KEY2 VARCHAR(16777216),
	SEARCH_QUERY VARCHAR(16777216),
	CREATED_BY VARCHAR(16777216) DEFAULT CURRENT_USER(),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	IS_FAVORITE BOOLEAN DEFAULT FALSE,
	EXECUTION_COUNT NUMBER(38,0) DEFAULT 0,
	LAST_EXECUTED TIMESTAMP_NTZ(9)
);

-- お知らせ管理テーブル
CREATE OR REPLACE TABLE ANNOUNCEMENTS (
    ANNOUNCEMENT_ID NUMBER AUTOINCREMENT,
    TITLE VARCHAR(500),
    MESSAGE VARCHAR(5000),
    ANNOUNCEMENT_TYPE VARCHAR(50), -- 'info', 'warning', 'error', 'success'
    PRIORITY NUMBER DEFAULT 99, -- 数字が小さいほど優先度高
    START_DATE DATE,
    END_DATE DATE,
    SHOW_FLAG BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER(),
    PRIMARY KEY (ANNOUNCEMENT_ID)
);

-- デモ用お知らせデータ
INSERT INTO ANNOUNCEMENTS (TITLE, MESSAGE, ANNOUNCEMENT_TYPE, PRIORITY, START_DATE, END_DATE, SHOW_FLAG)
VALUES 
('アプリへようこそ', 'このアプリはSnowflake上のデータを探索するためのツールです。定型検索・非定型検索機能をお試しください。', 'info', 1, CURRENT_DATE(), DATEADD(month, 6, CURRENT_DATE()), TRUE);

-- ========================================
-- 3.SiSアプリのデプロイ
-- ========================================

-- API連携
CREATE OR REPLACE API INTEGRATION git_api_integration
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/sfc-gh-kmotokubota/')
  ENABLED = TRUE;

-- Git連携
CREATE OR REPLACE GIT REPOSITORY GIT_INTEGRATION_FOR_HANDSON
  API_INTEGRATION = git_api_integration
  ORIGIN = 'https://github.com/sfc-gh-kmotokubota/simple_serach_streamlit_app.git';

-- Gitのソースコードを元にStreamlit in Snowflakeの作成
CREATE OR REPLACE STREAMLIT simple_search_app
    FROM @GIT_INTEGRATION_FOR_HANDSON/branches/main/simple_search_app
    MAIN_FILE = 'streamlit_app.py'
    QUERY_WAREHOUSE = COMPUTE_WH;

